export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_MAP = 'SET_MAP';
export const ADD_EVENT = 'ADD_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FIND_LOCATION_BY_COORDS = 'FIND_LOCATION_BY_COORDS';
export const FIND_LOCATION_BY_NAME = 'FIND_LOCATION_BY_NAME';
export const FIND_ROUTE_DISTANCE = 'FIND_ROUTE_DISTANCE';
